server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: health-apis

health:
  security:
    api-key:
      header: X-API-KEY
      value: ${HEALTH_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
